services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: spotifudb
    ports:
      - '5440:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
